spring:
  #sql
  sql:
    init:
      # DB에 데이터 없으면 always 후 never로 끄지않으면 키 충돌 발생
      mode: never
  # email
  application:
    name: sbb
  main:
    allow-bean-definition-overriding: true
  # 코드 수정 자동 반영
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # DATABASE
  h2:
    console:
      path: /h2-console
    enabled: true
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE