name: Scheduled Workflow

on:
  schedule:
    - cron: '25 0 * * *' # UTC + 9

jobs:
  daily_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Current Date
        id: date
        run: echo "BRANCH_NAME=$(date +'%Y-%m-%d')" >> $ENV

      - name: Create PR from dev to main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          # dev 브랜치 체크아웃 및 최신 상태로 업데이트
          git checkout dev
          git pull origin dev
          
          # 새 브랜치 생성
          git checkout -b "$BRANCH_NAME"
          git pull origin main
          
          # dev와 main 병합 시도
          git merge dev --no-ff || (echo "Merge conflict detected. Aborting." && exit 1)

          # 새 브랜치 푸시
          git push origin "$BRANCH_NAME"
          
          # PR 생성 데이터 준비 및 요청
          PR_DATA=$(jq -n \
            --arg title "Daily Deploy: dev to main" \
            --arg body "데일리 PR" \
            --arg head "$BRANCH_NAME" \
            --arg base "main" \
            '{"title":$title, "body":$body, "head":$head, "base":$base}')
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               -d "$PR_DATA"
